#!/usr/bin/env ruby
require 'saml/kit'

saml = STDIN.read

binding = Saml::Kit::HttpPostBinding.new(location: '')
xml = binding.deserialize('SAMLRequest' => saml).to_xml
puts Nokogiri::XML(xml).to_xml(indent: 2)
