#!/usr/bin/env ruby
require 'saml/kit'

Saml::Kit.deprecate("Use the 'saml-kit-cli' gem instead. saml-kit-decode-http-redirect*")

input = STDIN.read
binding = Saml::Kit::Bindings::HttpRedirect.new(location: '')

uri = URI.parse(input) rescue nil
if uri
  query_params =  Hash[uri.query.split('&').map { |x| x.split('=', 2) }]
  puts binding.deserialize(query_params).to_xml(pretty: true)
else
  puts binding.deserialize('SAMLRequest' => input).to_xml(pretty: true)
end
