#!/usr/bin/env ruby
require 'saml/kit'

Saml::Kit.deprecate("Use the 'saml-kit-cli' gem instead. saml-kit-create-self-signed-certificate")

puts 'Enter Passphrase:'
passphrase = STDIN.read.strip
certificate, private_key = ::Xml::Kit::SelfSignedCertificate.new.create(passphrase: passphrase)

puts '** BEGIN File Format **'
print certificate
puts private_key
puts '***********************'

puts

puts '*** BEGIN ENV Format **'
puts certificate.inspect
puts private_key.inspect
puts '***********************'

puts
puts 'Private Key Passphrase:'
puts passphrase.inspect
