#!/usr/bin/env ruby
# frozen_string_literal: true

require 'saml/kit'

message = "Use the 'saml-kit-cli' gem instead. saml-kit-decode-http-post"
Saml::Kit.deprecate(message)

saml = STDIN.read
binding = Saml::Kit::Bindings::HttpPost.new(location: '')
puts binding.deserialize('SAMLRequest' => saml).to_xml(pretty: true)
