#!/usr/bin/env ruby
# frozen_string_literal: true

require 'saml/kit'

message = "Use the 'saml-kit-cli' gem instead. saml-kit-decode-http-redirect*"
Saml::Kit.deprecate(message)

input = STDIN.read
binding = Saml::Kit::Bindings::HttpRedirect.new(location: '')

uri = begin
        URI.parse(input)
      rescue StandardError
        nil
      end
if uri
  query_params = Hash[uri.query.split('&').map { |x| x.split('=', 2) }]
  puts binding.deserialize(query_params).to_xml(pretty: true)
else
  puts binding.deserialize('SAMLRequest' => input).to_xml(pretty: true)
end
